# If this Travis script breaks, see the original documentation here:
# https://jekyllrb.com/docs/continuous-integration/travis-ci/

language: ruby
rvm:
  - 2.5.1
sudo: false

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

cache: bundler # caching bundler gem packages will speed up build

script:
  - bundle exec jekyll build --strict_front_matter
  - bundle exec htmlproofer ./_site --check-html --only-4xx --http-status-ignore 429 --alt-ignore '/.*/'

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
